class CustomError(Exception):
    """Кастомное исключение."""

    pass
